import type {Metadata} from "next";

import "./globals.css";

import AuthProvider from "@/contexts/SessionProvider";
import {fontBranded} from "@/utils/fonts";
import UIProvider from "@/contexts/UIProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app"
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${fontBranded.variable}`}>
                <AuthProvider>
                    <UIProvider>{children}</UIProvider>
                </AuthProvider>
            </body>
        </html>
    );
}
